services:
  modulith-db:
    image: postgres:16-alpine
    container_name: modulith-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: modulith
      POSTGRES_PASSWORD: modulith_pass
      POSTGRES_DB: modulith_db
    ports:
      - "5432:5432"
    volumes:
      - modulith_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: modulith-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@modulith.dev
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - modulith-db

volumes:
  modulith_pgdata:
